version: "3"

services:

  runtime-setup:
    image: swift-async-algorithms:20.04-5.7
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.7"

  build:
    image: swift-async-algorithms:20.04-5.7

  test:
    image: swift-async-algorithms:20.04-5.7
    environment: []
      #- SANITIZER_ARG: "--sanitize=thread"
      #- TSAN_OPTIONS: "no_huge_pages_for_shadow=0 suppressions=/code/tsan_suppressions.txt"

  shell:
    image: swift-async-algorithms:20.04-5.7
